plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

remote_theme: pages-themes/hacker@v0.2.0

relative_links:
  enabled: true
  collections: true

title: Star Citizen Roleplay
description: Star Citizen Roleplay Character Sheet

include:
  - src/header.md
  - src/main.md
  - src/footer.md