plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

remote_theme: pages-themes/hacker@v0.2.0

relative_links:
  enabled: true
  collections: true


title: Arasil
description: Star Citizen GrimHex Roleplay
